<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUxt52F5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUxt52F5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUxt52F5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUxt52F5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUxt52F5\App_KernelDevDebugContainer([
    'container.build_hash' => 'Uxt52F5',
    'container.build_id' => 'e8c42091',
    'container.build_time' => 1716580863,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUxt52F5');
