<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHAgnxTg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHAgnxTg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHAgnxTg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHAgnxTg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHAgnxTg\App_KernelDevDebugContainer([
    'container.build_hash' => 'HAgnxTg',
    'container.build_id' => '6a81134c',
    'container.build_time' => 1716561155,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHAgnxTg');
